export type BangkokOtaEntry={
  tripadvisor:{score:string;reviews:string;title:string;url:string};
  chinese:{site:string;score?:string;reviews?:string;note:string;url?:string};
  google?:{score:string;reviews:string;note:string;url:string};
  recommend:string;
  caution:string;
  checked:string;
};

const O=(tripadvisor:BangkokOtaEntry['tripadvisor'],chinese:BangkokOtaEntry['chinese'],recommend:string,caution:string):BangkokOtaEntry=>({tripadvisor,chinese,recommend,caution,checked:'2026-09-12'});
const TA=(score:string,reviews:string,title:string,url:string)=>({score,reviews,title,url});

const records:Record<string,BangkokOtaEntry>={
 'Aman Nai Lert Bangkok':O(TA('4.8/5','23','Aman Nai Lert Bangkok','https://www.tripadvisor.com/Hotel_Review-g293916-d23951986-Reviews-Aman_Nai_Lert_Bangkok-Bangkok.html'),{site:'携程',score:'4.7/5',reviews:'51','note':'住客称环境安静、服务有情绪价值；新开业，中文内容仍少。',url:'https://mm.ctrip.com/html5/hotel/hoteldetail/119966068.html'},'Aman 服务、接机与管家体验突出，99㎡起的房间和安静环境是核心。','约 US$1,300/晚，性价比争议大；开业初期有小瑕疵，城市景观不如河畔酒店。'),
 'Capella Bangkok':O(TA('4.9/5','1,197','Capella Bangkok','https://www.tripadvisor.com/Hotel_Review-g293916-d20235329-Reviews-Capella_Bangkok-Bangkok.html'),{site:'携程',score:'4.6/5',reviews:'206',note:'房间、早餐、河畔别墅与接送获得好评；中文样本也提醒高价时性价比下降。',url:'https://wap.ctrip.com/html5/hotel/hoteldetail/35898426.html'},'服务、餐饮和河景口碑顶级，河畔别墅与早餐尤其强。','接驳船约每小时一班；高价日期性价比存疑，也有鸡尾酒课程差评。'),
 'Four Seasons Bangkok':O(TA('4.6/5','415','Four Seasons Hotel Bangkok at Chao Phraya River','https://www.tripadvisor.com/Hotel_Review-g293916-d19729162-Reviews-Four_Seasons_Hotel_Bangkok_at_Chao_Phraya_River-Bangkok.html'),{site:'携程',score:'4.6/5',reviews:'337',note:'中文点评认可河畔度假感、早餐与泳池。',url:'https://mm.ctrip.com/html5/hotel/hoteldetail/48004058.html'},'城市度假村氛围、河景、长泳池、早餐与接驳船都稳定。','有账单多收与补救不力的个案；泳池结构被指显旧，周边堵车。'),
 '曼谷文华东方':O(TA('4.8/5','6,534','Mandarin Oriental Bangkok','https://www.tripadvisor.com/Hotel_Review-g293916-d301411-Reviews-Mandarin_Oriental_Bangkok-Bangkok.html'),{site:'携程',score:'4.7/5',reviews:'268',note:'中文住客突出“老钱感”、无微不至的服务与早餐；马蜂窝酒店页为4.8分。',url:'https://mm.ctrip.com/html5/hotel/hoteldetail/995162.html'},'150年历史、服务、河景和水边早餐形成曼谷经典体验。','价格高、升级严格；部分浴室偏暗，部分设施在河对岸，早餐连续住会重复。'),
 'The Siam':O(TA('4.8/5','1,050','The Siam','https://www.tripadvisor.com/Hotel_Review-g293916-d2553477-Reviews-The_Siam-Bangkok.html'),{site:'携程',score:'4.6/5',reviews:'76',note:'中文点评突出古董收藏、热情服务和单点式无限量早餐。',url:'https://mm.ctrip.com/html5/hotel/hoteldetail/703049.html'},'私人管家、码头游船、古董收藏与低层河畔宅邸感独特。','杜斯特区位置偏，距轨道交通远；适合宅酒店，不适合密集跨城行程。'),
 'Sorn':O(TA('4.3/5','36','Sorn Fine Southern Cuisine','https://www.tripadvisor.com/Restaurant_Review-g293916-d15398467-Reviews-Sorn_Fine_Southern_Cuisine-Bangkok.html'),{site:'大众点评快照',note:'精选内容称泰南食材与创意“绝对值得”，但页面需登录，样本来自公开快照。'},'三星泰南菜，食材与创意得到中英文样本明确认可。','全泰最难订之一，需提前数月；TA样本仅36条且有预订流程差评。'),
 'Sühring':O(TA('4.5/5','579','Sühring','https://www.tripadvisor.com/Restaurant_Review-g293916-d10108291-Reviews-Suhring-Bangkok.html'),{site:'大众点评快照',note:'中文样本好评为主，也明确提示人均约2,000元以上与高额加成。'},'服务稳定、现代德国菜辨识度高，整体星级体验获多数支持。','价格很高，需提前预约；个别评价批评菜品与配酒。'),
 'Gaggan':O(TA('4.1/5','69','Gaggan Anand','https://www.tripadvisor.com/Restaurant_Review-g293916-d19602736-Reviews-Gaggan_Anand-Bangkok.html'),{site:'中文旅行笔记',note:'公开中文样本同时出现“趣味体验”和“味道一般”，评价明显分化。'},'表演式长菜单、互动和创意感鲜明，适合想要一次戏剧化晚餐的人。','口味、主理人态度与座位安排存在强烈负评；份量大，且需提前很久订。'),
 'Côte by Mauro Colagreco':O(TA('4.8/5','196','Côte by Mauro Colagreco','https://www.tripadvisor.com/Restaurant_Review-g293916-d21509083-Reviews-Cote_by_Mauro_Colagreco-Bangkok.html'),{site:'大众点评精选',note:'中文精选把它列为浪漫氛围餐厅，强调法餐、地中海风味与本地食材。'},'嘉佩乐内的二星法餐，食物、服务、河畔位置和仪式感都强。','价格高、周一闭店；中文点评样本比TA少。'),
 'Le Du':O(TA('4.0/5','575','Le Du Restaurant','https://www.tripadvisor.com/Restaurant_Review-g293916-d5579925-Reviews-Le_Du_Restaurant-Bangkok.html'),{site:'大众点评精选',note:'中文榜单强调亚洲50佳与黑珍珠经历，公开估算人均约1,000–1,350元。'},'创意泰菜与本地海鲜的现代呈现仍有高质量推荐样本。','TA负评比例不可忽略：服务冷漠、溢价与固定菜单收费沟通均有投诉。'),
 'Nusara':O(TA('4.1/5','27','Nusara','https://www.tripadvisor.com/Restaurant_Review-g293916-d25185610-Reviews-Nusara-Bangkok.html'),{site:'大众点评快照 / 什么值得买',note:'中文样本认可现代泰菜与卧佛寺屋顶景；同时明确需提前且全额预付。'},'现代泰菜、个性化服务与老城屋顶景形成完整体验。','TA只有27条；全额预付、预订纠纷与性价比争议需要权衡。'),
 'Potong':O(TA('4.4/5','45','Potong Restaurant','https://www.tripadvisor.com/Restaurant_Review-g293916-d23727707-Reviews-Potong_Restaurant-Bangkok.html'),{site:'大众点评',score:'4.7/5',note:'人均约¥1,887；中文样本认可家族故事与历史建筑，也有“失望透顶”的反向体验。'},'主厨Pam家族故事、老建筑和沉浸式动线很有辨识度。','口味两极，有油腻、过誉与高价投诉；极难订位。'),
 'Nahm':O(TA('3.9/5','3,377','Nahm Bangkok','https://www.tripadvisor.com/Restaurant_Review-g293916-d1890598-Reviews-Nahm-Bangkok.html'),{site:'大众点评快照 / 猫途鹰',score:'3.9/5',note:'中文样本认可传统食材与老牌米其林，也集中出现偏咸、失望反馈。'},'老牌米其林泰餐，传统食材与摩登环境仍有吸引力。','偏咸是重复出现的问题；素食表现与性价比也有明确负评。'),
 'Jay Fai':O(TA('3.5/5','903','Raan Jay Fai','https://www.tripadvisor.com/Restaurant_Review-g293916-d3703955-Reviews-Raan_Jay_Fai-Bangkok.html'),{site:'大众点评快照',note:'中文内容既认可传奇主厨和蟹肉蛋卷，也记录数小时排队与劝退观点。'},'传奇街头米其林与蟹肉蛋卷有很强打卡和文化价值。','3.5分说明争议很大：贵、服务差、只收现金/不收卡、排队数小时。'),
 'Thipsamai':O(TA('4.1/5','2,252','Pad Thai Thipsamai','https://www.tripadvisor.com/Restaurant_Review-g293916-d3710114-Reviews-Pad_Thai_Thipsamai_Restaurant-Bangkok.html'),{site:'大众点评精选',note:'中文内容把它作为老字号地道风味；需注意原店与商场分店不要混用口碑。'},'1966年老店，蛋包炒河粉与性价比有稳定支持。','口味明显偏甜；有人认为游客化、过誉，热门时段要排队。'),
 '耀华力夜市 / T&K':O(TA('3.9/5','1,107','T&K Seafood','https://www.tripadvisor.com/Restaurant_Review-g293916-d1220300-Reviews-T_K_Seafood-Bangkok.html'),{site:'大众点评快照 / 什么值得买',note:'中文样本认可海鲜新鲜和夜市氛围；人均约166元，但价格是否合理存在分歧。'},'唐人街深夜海鲜、品种和烟火气适合扫街路线。','环境普通、游客化与“宰客感”争议；不必当作正式大餐。'),
 'Or Tor Kor Market':O(TA('4.3/5','510','Or Tor Kor Market','https://www.tripadvisor.com/Attraction_Review-g293916-d1008549-Reviews-Or_Tor_Kor_OTK_Market-Bangkok.html'),{site:'马蜂窝 / 携程',note:'中文攻略强调市场干净、品质高以及CNN全球十佳菜市场背景。'},'水果、熟食、整洁度和交通便利性都获得中英文认可。','价格高于普通市场，也比本地湿市场更游客化。'),
 '大皇宫 & 玉佛寺':O(TA('4.2/5','36,104','The Grand Palace','https://www.tripadvisor.com/Attraction_Review-g293916-d317603-Reviews-The_Grand_Palace-Bangkok.html'),{site:'携程 / 马蜂窝',note:'中文攻略认可鎏金佛塔、壁画与历史感，反复建议早去避开人潮。'},'曼谷最核心的建筑与宗教地标；同区可串联卧佛寺。','游客极多、着装严格；周边常见“今日关闭”等骗局，建议早到。'),
 '郑王庙 Wat Arun':O(TA('4.4/5','21,550','Temple of Dawn (Wat Arun)','https://www.tripadvisor.com/Attraction_Review-g293916-d317504-Reviews-Temple_Of_Dawn_Wat_Arun-Bangkok.html'),{site:'携程 / 大众点评',note:'中文攻略认可日落与夜景，也记录停车、摩的被加价的案例。'},'瓷片佛塔、河景与傍晚光线非常有辨识度。','白天暴晒且人多；停车/摩的可能加价，优先搭船并在清晨或傍晚去。'),
 '四面佛':O(TA('4.2/5','2,715','Erawan Shrine','https://www.tripadvisor.com/Attraction_Review-g293916-d552410-Reviews-Erawan_Shrine_Thao_Mahaprom_Shrine-Bangkok.html'),{site:'携程 / 马蜂窝',note:'中文攻略提醒参拜礼仪与不要过度拍摄；适合和暹罗商圈顺路。'},'市中心、BTS可达，100泰铢左右的供品套装让参拜安排简单。','本体很小，不值得脱离商圈专程往返；拍摄和参拜需尊重礼仪。'),
 '恰图恰周末市场':O(TA('4.3/5','18,376','Chatuchak Weekend Market','https://www.tripadvisor.com/Attraction_Review-g293916-d450971-Reviews-Chatuchak_Weekend_Market-Bangkok.html'),{site:'马蜂窝 / 携程',note:'中文攻略把它列为周末淘宝重点，并建议和暹罗商圈分半天安排。'},'品类全、可讲价，适合淘宝和观察曼谷市集文化。','规模巨大容易迷路，炎热拥挤；完整营业集中在周末，进场先拍地图。'),
 '金山寺':O(TA('4.4/5','5,188','The Golden Mount (Wat Saket)','https://www.tripadvisor.com/Attraction_Review-g293916-d456261-Reviews-The_Golden_Mount_Wat_Saket-Bangkok.html'),{site:'携程 / 中文旅行笔记',note:'中文资料列出07:00–19:00，并提示登顶约344级台阶。'},'相对清净的城市制高点，日落和360度视野是核心。','约344级台阶，白天炎热；开放时间仍需出发前复核。'),
 'Mahanakhon 天空步道':O(TA('4.5/5','1,168','King Power Mahanakhon','https://www.tripadvisor.com/Attraction_Review-g293916-d14135436-Reviews-King_Power_Mahanakhon-Bangkok.html'),{site:'携程 / 微博 / 马蜂窝',note:'中文资料认可314米高空景观与玻璃步道，也给出帝国大厦55层咖啡店的平替建议。'},'日落、夜景和玻璃步道可在一次登高里完成。','票价约880–1,050泰铢且会变化；恐高或天气差时不值得硬上。'),
 'ICONSIAM':O(TA('4.4/5','1,755','ICONSIAM','https://www.tripadvisor.com/Attraction_Review-g293916-d15354570-Reviews-ICONSIAM-Bangkok.html'),{site:'马蜂窝 / 携程',note:'中文样本认为室内水上市场比预期小，但认可免费船、购物与演出选择。'},'河畔地标商场，SookSiam、美食、购物与夜景可以一站完成。','人多、消费偏高；室内水上市场规模可能低于预期。'),
 '唐人街耀华力路':O(TA('4.0/5','8,299','Chinatown Bangkok','https://www.tripadvisor.com/Attraction_Review-g293916-d447272-Reviews-Chinatown_Bangkok-Bangkok.html'),{site:'马蜂窝 / 携程',note:'中文攻略突出街头美食和MRT Wat Mangkon交通，适合夜间扫街。'},'美食摊位集中、价格亲民，霓虹和烟火气很强。','夜晚极拥挤混乱，卫生与气味因人而异；整体体验可能低于网红预期。'),
 '伦披尼公园':O(TA('4.3/5','7,833','Lumpini Park','https://www.tripadvisor.com/Attraction_Review-g293916-d456170-Reviews-Lumpini_Park-Bangkok.html'),{site:'去哪儿',score:'4.3/5',reviews:'132',note:'中文点评认为黄昏最热闹，可运动、看水巨蜥和体验免费鸭子船。'},'免费城市绿洲，晨跑、黄昏散步和观察水巨蜥都适合。','维护评价不一；鸭子船有75kg/人的限重反馈，蚊虫也需准备。')
};

records['888 Hokkien Mee（Three Road）']={tripadvisor:{score:'4.5/5',reviews:'114',title:'Three Road 888 Hokkien Mee',url:'https://www.tripadvisor.ie/Restaurant_Review-g298303-d10413607-Reviews-Three_Road_888_Hokkien_Mee-George_Town_Penang_Island_Penang.html'},chinese:{site:'Trip.com',score:'4.6/5',reviews:'37',note:'页面显示摊位在67-A, Lebuh Presgrave；公开中文样本认可浓郁虾汤，也提示只收现金。',url:'https://www.trip.com/restaurant/malaysia/george-town/detail/888-hokkien-mee-18054372/'},google:{score:'4.2/5',reviews:'3,426',note:'地址与坐标已和研究记录交叉核对',url:'https://www.google.com/maps/search/888%20hokkien%20mee'},recommend:'米其林指南收录，虾汤鲜甜浓郁；烧肉、卤排骨与隔壁摊蚝煎是评价中反复出现的加点。',caution:'长队、闷热、份量偏小与自助端盘是反复出现的提醒；建议15:00开门前后到。',checked:'2026-09-13'};

records['卧佛寺 Wat Pho']={tripadvisor:{score:'4.7/5',reviews:'近期页面样本',title:'Wat Pho, Temple Of The Reclining Buddha',url:'https://www.TripAdvisor.ca/Attraction_Review-g293916-d33229338-Reviews-Wat_Pho_Temple_Of_The_Reclining_Buddha-Bangkok.html'},chinese:{site:'Trip.com',note:'地点页与中文旅行内容交叉支持300 THB门票、08:00–18:30开放时段；最终以现场公告为准。',url:'https://www.trip.com/moments/detail/bangkok-191-119157861/'},recommend:'46米卧佛、寺院建筑、四王塔与传统按摩学校适合和大皇宫顺路串联；近期评价建议先看卧佛再逛庭院。',caution:'热门机位和下午时段拥挤；门外有“今日关闭”骗局反馈，直接走有清晰标识的官方入口。',checked:'2026-09-13'};

export const bangkokOta:Record<string,BangkokOtaEntry>=records;
