import overview from './assets/maps/overview.png';
import d1 from './assets/maps/day-1.png';
import d2 from './assets/maps/day-2.png';
import d3 from './assets/maps/day-3.png';
import d4 from './assets/maps/day-4.png';
import d5 from './assets/maps/day-5.png';
import d6 from './assets/maps/day-6.png';
import d7 from './assets/maps/day-7.png';
import d8 from './assets/maps/day-8.png';
import d9 from './assets/maps/day-9.png';
import d10 from './assets/maps/day-10.png';
import d11 from './assets/maps/day-11.png';
import d12 from './assets/maps/day-12.png';
import d13 from './assets/maps/day-13.png';
import d14 from './assets/maps/day-14.png';
import d15 from './assets/maps/day-15.png';
import d16 from './assets/maps/day-16.png';
import d17 from './assets/maps/day-17.png';
import d18 from './assets/maps/day-18.png';
import d19 from './assets/maps/day-19.png';
import d20 from './assets/maps/day-20.png';
export const overviewMap=overview;
export const dayMaps=[d1,d2,d3,d4,d5,d6,d7,d8,d9,d10,d11,d12,d13,d14,d15,d16,d17,d18,d19,d20];
